### ISSUE TITLE
not an issue but a question

### ISSUE THREAD

**Issue by adcdam** [johanmalm/trappist#1]
Hi is this still in development?

**Comment by johanmalm** [comment]
Yes, but not _active_ development. I wrote it when I had a moment of inspiration and just wanted to have a go at writing a simple Wayland client.

There are two reasons for the stagnation. Firstly that I'm prioritizing `labwc`, and secondly that I couldn't make up my mind what a sensible scope is for `trappist`.

Regarding scope, I think the main things missing is pipe-menus and the ability to configure style/position. I can't make up my mind how to do the configuration though.

I'm inclined to let `labwc-menu-generator` deal with finding icons according to theme - and anything else relating to menu content.

**Comment by 01micko** [comment]
So, what about `yaml` for config? Don't need too much, 

- font
- bgcolor
- fgcolor
- highlight colors
- border color

**Comment by johanmalm** [comment]
> So, what about `yaml` for config? Don't need too much,
> 
>     * font
> 
>     * bgcolor
> 
>     * fgcolor
> 
>     * highlight colors
> 
>     * border color

Have just started using `ini` as it's easier for me to implement.

**Comment by pfr-dev** [comment]
with `wld` and `swc` becoming more popular recently, along with the minimal wayland setups (See https://wayland.fyi ), I came across Trappist as a way to add a standalone right-click desktop menu to some of these minimal window managers. Just bumping this to show interest, that's all.
